ks-stage-deploy:
  tags:
    - ks-stage
  script:
    - hostname
    - cd /opt/knowledge-space-new/
    - sudo git checkout stage
    - sudo git pull
    - sudo npm run build
    - sudo service application restart
    - sudo service nginx restart
