ks-stage-deploy:
  tags:
    - ks-stage
  script:
    - hostname
    - whoami
    - cd /opt/knowledge-space-new/
    - git checkout -f stage
    - git pull
    - npm run build
    - sudo service application restart
    - sudo service nginx restart
